auto_login: No
username: ""
password: ""
base_dir: "~/Documents/Lectures"
concurrent_downloads: 4
progress_bar_size: 30
exclude: ""
login_service_url: "https://login.manchester.ac.uk/cas/login"
video_service_base_url: "https://video.manchester.ac.uk"